media: files
content:
  - name: posts
    label: Posts
    path: _posts
    type: collection
    view:
      fields: [ title, date ]
    fields:
      - name: title
        label: Title
        type: string
      - name: description
        label: Description
        type: string
      - name: image
        label: Image
        type: image
      - name: layout
        type: string
        hidden: true
      - name: comments
        label: Comments
        type: boolean
        default: true
      - name: body
        label: Body
        type: rich-text