media: files
content:
  - name: bob
    label: Bob
    path: bob
    type: file
    fields:
      - name: title
        type: string
  - name: posts
    label: Posts
    type: collection
    path: _posts
    view:
      fields: [ title, date ]
    fields:
      - { name: title, label: Title, type: string }
      - { name: layout, type: string, hidden: true, default: post }
      - { name: date, label: Date, type: date }
      - { name: comments, label: Comments, type: boolean, default: true }
      - { name: description, label: Description, type: string, options: { maxlength: 160 } }
      - { name: image, label: Image, type: image }
      - { name: body, label: Body, type: rich-text }