# Site settings
title: "Ronan Berder's blog"
email: "info@wiredcraft.com"
description: Rambles about entrepreneurship, China, tech and design
baseurl: ""
url: "https://ronanberder.com"
keywords:
- China
- design
- technology
- entrepreneurship

# SEO
twitter:
  username: hunvreus
logo: /images/logo.png
social:
  name: Ronan Berder
  links:
    - https://www.facebook.com/profile.php?id=100006671895640
    - https://twitter.com/hunvreus
    - https://cn.linkedin.com/in/ronanberder
    - https://github.com/hunvreus

# Build settings
exclude: ['README.md']
permalink: pretty

# Plugins
gems:
  - jekyll-sitemap
  - jekyll-seo-tag
